sudo: true
language: python
dist: trusty
matrix:
  include:
    - python: "3.5"
before_install:
  - "sudo apt-get update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latexmk poppler-utils latex-xcolor  lmodern texlive-xetex texlive-generic-recommended"
install:
  - git clone https://github.com/lsst/lsst-texmf.git
script:
  - export TEXMFHOME=./lsst-texmf/texmf
  - make
